# docker-compose.yml
version: "3.9"

services:
  loan-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loan_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default